name: Build
env:
  RUST_BACKTRACE: 1

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2025, macos-14]
        rust: [stable]
        experimental: [false]
        include:
          - os: ubuntu-24.04
            rust: nightly
            experimental: true
          - os: windows-2025
            rust: nightly
            experimental: true
          - os: macos-14
            rust: nightly
            experimental: true

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Dependencies (Linux)
      run: sudo apt-get update && sudo apt-get install libdbus-1-dev
      if: matrix.os == 'ubuntu-24.04'

    - name: Install Rust
      run: |
        rustup toolchain install ${{ matrix.rust }} --profile minimal
        rustup component add rustfmt --toolchain ${{ matrix.rust }}
        rustup component add clippy --toolchain ${{ matrix.rust }}

    - name: Check format
      shell: bash
      run: rustup run ${{ matrix.rust }} cargo fmt --all -- --check

    - name: Clippy
      shell: bash
      run: rustup run ${{ matrix.rust }} cargo clippy --all -- -D warnings

    - name: Build
      shell: bash
      run: rustup run ${{ matrix.rust }} cargo build --all

    - name: Test
      shell: bash
      run: rustup run ${{ matrix.rust }} cargo test --all

